<template>
    <div>
        <div>
            <el-input
                placeholder="电子邮件地址"
                suffix-icon="el-icon-message"
                v-model="input2">
            </el-input>
            <el-input
                placeholder="密码"
                suffix-icon="el-icon-setting"
                v-model="input2">
            </el-input>
        </div>  
        <span>还没有账号吗？</span>
        <span>注册</span>
    </div>
</template>
